.PHONY: clean All

All:
	@echo "----------Building project:[ log_reader - Debug ]----------"
	@cd "log_reader" && "$(MAKE)" -f  "log_reader.mk"
clean:
	@echo "----------Cleaning project:[ log_reader - Debug ]----------"
	@cd "log_reader" && "$(MAKE)" -f  "log_reader.mk" clean
