.PHONY: clean All

All:
	@echo "----------Building project:[ examples - Debug ]----------"
	@"$(MAKE)" -f  "examples.mk"
clean:
	@echo "----------Cleaning project:[ examples - Debug ]----------"
	@"$(MAKE)" -f  "examples.mk" clean
