.PHONY: clean All

All:
	@echo "----------Building project:[ lists - Debug ]----------"
	@"$(MAKE)" -f  "lists.mk"
clean:
	@echo "----------Cleaning project:[ lists - Debug ]----------"
	@"$(MAKE)" -f  "lists.mk" clean
