.PHONY: clean All

All:
	@echo "----------Building project:[ node - Debug ]----------"
	@"$(MAKE)" -f  "node.mk"
clean:
	@echo "----------Cleaning project:[ node - Debug ]----------"
	@"$(MAKE)" -f  "node.mk" clean
