.PHONY: clean All

All:
	@echo "----------Building project:[ circular_list - Debug ]----------"
	@cd "circular_list" && "$(MAKE)" -f  "circular_list.mk"
clean:
	@echo "----------Cleaning project:[ circular_list - Debug ]----------"
	@cd "circular_list" && "$(MAKE)" -f  "circular_list.mk" clean
