.PHONY: clean All

All:
	@echo "----------Building project:[ SKB_Energiya - Debug ]----------"
	@cd "/home/user/codelite_project/cpp_projects/SKB_Energiya/SKB_Energiya" && "$(MAKE)" -f  "SKB_Energiya.mk"
clean:
	@echo "----------Cleaning project:[ SKB_Energiya - Debug ]----------"
	@cd "/home/user/codelite_project/cpp_projects/SKB_Energiya/SKB_Energiya" && "$(MAKE)" -f  "SKB_Energiya.mk" clean
