.PHONY: clean All

All:
	@echo "----------Building project:[ sorting - Debug ]----------"
	@"$(MAKE)" -f  "sorting.mk"
clean:
	@echo "----------Cleaning project:[ sorting - Debug ]----------"
	@"$(MAKE)" -f  "sorting.mk" clean
