.PHONY: clean All

All:
	@echo "----------Building project:[ tree - Debug ]----------"
	@"$(MAKE)" -f  "tree.mk"
clean:
	@echo "----------Cleaning project:[ tree - Debug ]----------"
	@"$(MAKE)" -f  "tree.mk" clean
